### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by zixia** [Chatie/db#51]
When running the smoke testing script in Node.JS, the `@auth0/angular-jwt@2.0.0` throws an error message: **ReferenceError: window is not defined**

```shell
+node smoke-testing.js
/tmp/npm-pack-testing.5971/node_modules/@auth0/angular-jwt/bundles/core.umd.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(require("@angular/core"),require("@angular/common/http"),require("rxjs/operators"),require("rxjs/internal/observable/from")):"function"==typeof define&&define.amd?define(["@angular/core","@angular/common/http","rxjs/operators","rxjs/internal/observable/from"],e):"object"==typeof exports?exports["angular-jwt"]=e(require("@angular/core"),require("@angular/common/http"),require("rxjs/operators"),require("rxjs/internal/observable/from")):t["angular-jwt"]=e(t["@angular/core"],t["@angular/common/http"],t["rxjs/operators"],t["rxjs/internal/observable/from"])}(window,function(t,e,r,n){return function(t){var e={};function r(n){if(e[n])return e[n].exports;var o=e[n]={i:n,l:!1,exports:{}};return t[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=t,r.c=e,r.d=function(t,e,n){r.o(t,e)||Ob
ReferenceError: window is not defined
    at Object.<anonymous> (/tmp/npm-pack-testing.5971/node_modules/@auth0/angular-jwt/bundles/core.umd.js:1:704)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /tmp/npm-pack-testing.5971/node_modules/auth-angular/bundles/auth-angular.umd.js:2:111
    at Object.<anonymous> (/tmp/npm-pack-testing.5971/node_modules/auth-angular/bundles/auth-angular.umd.js:5:2)
```

### See Also

* Travis CI Log: <https://travis-ci.com/Chatie/db/jobs/126218183#L861>
* Issue for `@auth0/angular-jwt`: <https://github.com/auth0/angular2-jwt/issues/30#issuecomment-392423104>
* Angular Universal: <https://github.com/angular/universal/issues/830>

**Comment by zixia** [comment]
use `const jwtDecode = require('jwt-decode')` to prevent the namespace typing problem.
